### ISSUE TITLE
Ebuilds don't work as dependencies in other PHP software

### ISSUE THREAD

**Issue by r7l** [digital-competence/composer-ebuilds#6]
I am currently working on Ebuilds for PHPMD, PHPCS and similar tools. I am using your approach with `phpab` in `src_prepare` but the packages seem not to work outside of the scope of Composer. Not sure if that's some of the Composer magic i have yet to master or something else.

I have errors like this all over the place:

```
PHP Warning:  require_once(Fedora/Autoloader/autoload.php): Failed to open stream: No such file or directory in /usr/share/php/Symfony/Component/Filesystem/autoload.php on line 4
PHP Fatal error:  Uncaught Error: Failed opening required 'Fedora/Autoloader/autoload.php' (include_path='.:/usr/share/pdepend/bin/../main/php') in /usr/share/php/Symfony/Component/Filesystem/autoload.php:4
Stack trace:
#0 /usr/share/php/Fedora/Autoloader/functions.php(56): require_once()
#1 /usr/share/php/Fedora/Autoloader/Dependencies.php(78): Fedora\Autoloader\requireFile()
#2 /usr/share/php/Fedora/Autoloader/Dependencies.php(100): Fedora\Autoloader\Dependencies::process()
#3 /usr/share/pdepend/autoload.php(265): Fedora\Autoloader\Dependencies::required()
#4 /usr/share/pdepend/bin/pdepend(55): require_once('...')
#5 {main}
  thrown in /usr/share/php/Symfony/Component/Filesystem/autoload.php on line 4
```

It seems not to be able to figure where to load it from when using the `fedora2` template as it will render the include line with `require_once 'Fedora/Autoloader'.'/autoload.php';` unlike `fedora` template, which will be exactly the same but with a full path when using `require_once`. 

I've tried changing my Ebuilds and some of your Ebuilds locally to `fedora` and it works perfectly.

Would you be ok with me providing a PR and switch Ebuilds from `fedora2` to `fedora` template in order to make them work with other PHP software?

Or could you help me understand how to work with the Ebuilds having the current `fedora2` template?

**Comment by fcool** [comment]
Did you check your `include_path` - `php.ini` - setting? The autoloading and ebuild configuration relys on `/usr/share/php` being in it - as it is per default.

**Comment by r7l** [comment]
The `include_path` in php.ini remained untouched and is the default: `include_path = ".:/usr/share/php8:/usr/share/php"`. 

But your suggestion was actually right. Seems like `pdepend` is changing this setting in their code in order to fix unrelated issues: https://github.com/pdepend/pdepend/blob/master/src/bin/pdepend#L48

This breaks existing packages installed already when installing a package using `set_include_path()`, as `pdepend` broke your `dev-php/symfony-filesystem` package which had nothing to do with the idea to change the include path.

Seeing that brings me back to the question, why we should rely on a php.ini setting that can be changed by anyone within the PHP code. The Fedora autoloader will be exactly where Portage puts it anyways. So sticking to the Gentoo way would be a better option. Otherwise it would be a extra burden to constantly check 3rd party code for `set_include_path()` functions and fix them in code.
